/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.org.masterclass.rest;

import com.org.masterclass.model.Talk;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-09-14T11:36:36.683695Z[Etc/UTC]")

@Validated
@Api(value = "talks", description = "the talks API")
public interface TalksApi {

    default TalksApiDelegate getDelegate() {
        return new TalksApiDelegate() {};
    }

    /**
     * GET /talks : Get the list of talks during the congress
     * Return a list of talks during the congress
     *
     * @return OK (status code 200)
     */
    @ApiOperation(value = "Get the list of talks during the congress", nickname = "getTalks", notes = "Return a list of talks during the congress", response = Talk.class, responseContainer = "List", tags={ "talks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Talk.class, responseContainer = "List") })
    @RequestMapping(value = "/talks",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Talk>> getTalks() {
        return getDelegate().getTalks();
    }

}
